### ISSUE TITLE
User Story: Register for an account

### ISSUE THREAD

**Issue by sven-cork** [sven-cork/art-connoisseur#1]
As a site user I can effectively register for an account so that all features of the website can be utilised and 
a personal profile be created.

**Acceptance Criteria**:
Account registration link available on landing page and navbar in order to register for an account.

**Tasks**:
- [ ] Create a registration page. 
- [ ] Implement navbar link for account registration.
- [ ] Implement account registration link on landing page.
- [ ] Success message alert upon successfull registration.
