### ISSUE TITLE
User Story: Validate html, css, JavaScript and Python code

### ISSUE THREAD

**Issue by sven-cork** [sven-cork/art-connoisseur#19]
As a **site user** I can **access Art Connoisseur on the most common devices without unexpected disruptions or anomalies**. 

**Acceptance Criteria**:

**Tasks**:
- [ ] Validate html and css used on Art Connoisseur using [W3C ](https://validator.w3.org/) validation tool.
- [ ] Validate JavaScript used on Art Connoisseur using [jshint](https://jshint.com/).
- [ ] Validate Python used on Art Connoisseur using [GitPod](https://gitpod.io/) built in Python lintern.
