### ISSUE TITLE
Add 'TEST_VALIDATION.md' with all tests

### ISSUE THREAD

**Issue by sven-cork** [sven-cork/art-connoisseur#21]
Add 'TEST_VALIDATION.md' with manual tests, validations and Lighthouse test results.

**Acceptance Criteria**:

**Tasks**:
- [ ] Add all relevant manual tests for Art Connoisseur functionality.
- [ ] Add html, css, JavaScript and python validation results.
- [ ] Add Lighthouse performance results for all relevant pages or Art Connoisseur.
